#!/usr/bin/env bash
set -euo pipefail

# Baseline (NO RAG) per-paper SimulEval runner:
# - Uses per-paper extracted glossaries ONLY for bookkeeping/output naming
# - Does NOT enable RAG (no retrieval, no term_map injection)
#
# All user-facing strings are in English.

# ======Configuration=====
# Exit codes
EXIT_CONFIG_ERROR="2"
EXIT_DATA_ERROR="3"

# Repo
ROOT_DIR="/home/jiaxuanluo/InfiniSST"

# Base sweep script (baseline, no RAG)
BASE_SCRIPT="${ROOT_DIR}/documents/code/simuleval/rank16/baseline/bypass_simuleval_rank32_iter_0000452_hf_baseline_no_rag_sweep.sh"

# Dataset
DATA_ROOT="/mnt/taurus/data/siqiouyang/datasets/acl6060"
LANG_CODE_DEFAULT="zh"
LANG_CODE_OVERRIDE="${LANG_CODE_OVERRIDE:-}"
LANG_CODE="${LANG_CODE_DEFAULT}"
TARGET_LANG_OVERRIDE="${TARGET_LANG_OVERRIDE:-}"

# Per-paper glossaries (already generated by extract_acl_terms_from_paper_v2.py)
EXTRACTED_GLOSSARIES_DIR="${ROOT_DIR}/documents/data/data_pre/extracted_glossaries_by_paper"
EXTRACTED_GLOSSARY_MANIFEST="${ROOT_DIR}/documents/data/data_pre/extracted_glossary_by_paper_manifest.json"

# Output base (keep everything colocated with results)
OUTPUT_BASE_DEFAULT="/mnt/gemini/data2/jiaxuanluo/infinisst_omni_vllm_rank16_baseline_no_rag"
OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE_OVERRIDE:-}"
OUTPUT_BASE="${OUTPUT_BASE_DEFAULT}"

# Where to put per-paper artifacts (subset lists + mapping json)
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"

# Optional: restrict papers (space-separated paper_ids). Empty means all papers in dev.source.
PAPER_IDS_OVERRIDE="${PAPER_IDS_OVERRIDE:-}"

# Pass-through overrides to base sweep script (optional)
LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE:-}"
RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE:-}"  # kept for output naming compatibility
MODEL_NAME_OVERRIDE="${MODEL_NAME_OVERRIDE:-}"
RESUME_MODE="${RESUME_MODE:-0}"
CLEAN_OUTPUT_DIR_OVERRIDE="${CLEAN_OUTPUT_DIR_OVERRIDE:-}"
BACKUP_PARTIAL_RUNS="${BACKUP_PARTIAL_RUNS:-}"
SEED_OVERRIDE="${SEED_OVERRIDE:-}"
TEMPERATURE_OVERRIDE="${TEMPERATURE_OVERRIDE:-}"

# GPU selection override for base script (physical ids, e.g. "4,5")
CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE="${CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE:-4,5}"
# ======Configuration=====

if [[ -n "${LANG_CODE_OVERRIDE}" ]]; then
  LANG_CODE="${LANG_CODE_OVERRIDE}"
fi

if [[ -n "${OUTPUT_BASE_OVERRIDE}" ]]; then
  OUTPUT_BASE="${OUTPUT_BASE_OVERRIDE}"
fi

# Keep derived paths consistent after overrides.
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"

if [[ ! -f "${BASE_SCRIPT}" ]]; then
  echo "[ERROR] Base script not found: ${BASE_SCRIPT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -d "${DATA_ROOT}" ]]; then
  echo "[ERROR] DATA_ROOT not found: ${DATA_ROOT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -d "${EXTRACTED_GLOSSARIES_DIR}" ]]; then
  echo "[ERROR] Extracted glossaries dir not found: ${EXTRACTED_GLOSSARIES_DIR}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${EXTRACTED_GLOSSARY_MANIFEST}" ]]; then
  echo "[ERROR] Manifest not found: ${EXTRACTED_GLOSSARY_MANIFEST}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

PREP_SCRIPT="${ROOT_DIR}/documents/code/simuleval/prepare_extracted_glossary_by_paper_inputs.py"
if [[ ! -f "${PREP_SCRIPT}" ]]; then
  echo "[ERROR] Prepare script not found: ${PREP_SCRIPT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi

mkdir -p "${PAPER_INPUTS_DIR}"

echo "[INFO] Preparing per-paper dev lists (using pre-generated glossaries)..."
python3 "${PREP_SCRIPT}" \
  --extracted-glossaries-dir "${EXTRACTED_GLOSSARIES_DIR}" \
  --extracted-glossary-manifest "${EXTRACTED_GLOSSARY_MANIFEST}" \
  --data-root "${DATA_ROOT}" \
  --lang-code "${LANG_CODE}" \
  --output-dir "${PAPER_INPUTS_DIR}"

MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"
if [[ ! -f "${MAP_JSON}" ]]; then
  echo "[ERROR] Mapping JSON not found: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

PAPERS="$(
python3 - <<PY
import json
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
papers=obj.get('papers',{})
print(" ".join(sorted(papers.keys())))
PY
)"

if [[ -z "${PAPERS}" ]]; then
  echo "[ERROR] No papers prepared from mapping: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

if [[ -n "${PAPER_IDS_OVERRIDE}" ]]; then
  PAPERS="${PAPER_IDS_OVERRIDE}"
fi

echo "[INFO] OUTPUT_BASE=${OUTPUT_BASE}"
echo "[INFO] LANG_CODE=${LANG_CODE} TARGET_LANG_OVERRIDE='${TARGET_LANG_OVERRIDE:-<none>}'"
echo "[INFO] Baseline mode: RAG is disabled."
echo "[INFO] Papers to run: ${PAPERS}"
echo "[INFO] Overrides: lm='${LATENCY_MULTIPLIERS_OVERRIDE:-<none>}' k2='${RAG_K2_VALUES_OVERRIDE:-<none>}' resume='${RESUME_MODE}' seed='${SEED_OVERRIDE:-<default>}' temperature='${TEMPERATURE_OVERRIDE:-<default>}' model='${MODEL_NAME_OVERRIDE:-<default>}'"

for PAPER_ID in ${PAPERS}; do
  GLOSSARY_PATH="$(
  python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
item=obj.get('papers',{}).get(pid,{})
print(item.get('glossary_path',''))
PY
  )"
  SRC_LIST_OVERRIDE_LOCAL="$(
  python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
item=obj.get('papers',{}).get(pid,{})
print(item.get('src_list',''))
PY
  )"
  TGT_LIST_OVERRIDE_LOCAL="$(
  python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
item=obj.get('papers',{}).get(pid,{})
print(item.get('tgt_list',''))
PY
  )"

  if [[ -z "${GLOSSARY_PATH}" ]] || [[ ! -f "${GLOSSARY_PATH}" ]]; then
    echo "[WARN] Skip paper_id=${PAPER_ID}: glossary_path missing: ${GLOSSARY_PATH}" >&2
    continue
  fi
  if [[ -z "${SRC_LIST_OVERRIDE_LOCAL}" ]] || [[ ! -f "${SRC_LIST_OVERRIDE_LOCAL}" ]]; then
    echo "[WARN] Skip paper_id=${PAPER_ID}: src_list missing: ${SRC_LIST_OVERRIDE_LOCAL}" >&2
    continue
  fi
  if [[ -z "${TGT_LIST_OVERRIDE_LOCAL}" ]] || [[ ! -f "${TGT_LIST_OVERRIDE_LOCAL}" ]]; then
    echo "[WARN] Skip paper_id=${PAPER_ID}: tgt_list missing: ${TGT_LIST_OVERRIDE_LOCAL}" >&2
    continue
  fi

  echo "[INFO] ============================================================"
  echo "[INFO] Running paper_id=${PAPER_ID}"
  echo "[INFO] GLOSSARY_PATH(for naming)=${GLOSSARY_PATH}"
  echo "[INFO] SRC_LIST_OVERRIDE=${SRC_LIST_OVERRIDE_LOCAL}"
  echo "[INFO] TGT_LIST_OVERRIDE=${TGT_LIST_OVERRIDE_LOCAL}"

  GLOSSARY_PATHS_OVERRIDE="${GLOSSARY_PATH}" \
  SRC_LIST_OVERRIDE="${SRC_LIST_OVERRIDE_LOCAL}" \
  TGT_LIST_OVERRIDE="${TGT_LIST_OVERRIDE_LOCAL}" \
  OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE}" \
  MODEL_NAME_OVERRIDE="${MODEL_NAME_OVERRIDE}" \
  LANG_CODE_OVERRIDE="${LANG_CODE}" \
  TARGET_LANG_OVERRIDE="${TARGET_LANG_OVERRIDE}" \
  LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE}" \
  RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE}" \
  CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE="${CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE}" \
  CLEAN_OUTPUT_DIR_OVERRIDE="${CLEAN_OUTPUT_DIR_OVERRIDE}" \
  BACKUP_PARTIAL_RUNS="${BACKUP_PARTIAL_RUNS}" \
  RESUME_MODE="${RESUME_MODE}" \
  SEED_OVERRIDE="${SEED_OVERRIDE}" \
  TEMPERATURE_OVERRIDE="${TEMPERATURE_OVERRIDE}" \
  bash "${BASE_SCRIPT}"
done

echo "[INFO] Done."

