#!/usr/bin/env bash
set -euo pipefail

# Baseline (NO RAG) 5-paper combined test runner:
# - Prepares per-paper dev lists using extracted glossaries (bookkeeping only)
# - Concatenates 5 papers into a single combined dev list
# - Runs SimulEval ONCE on the combined list
# - Does NOT enable RAG (no retrieval, no term_map injection)
#
# All user-facing strings are in English.

# ======Configuration=====
# Exit codes
EXIT_CONFIG_ERROR="2"
EXIT_DATA_ERROR="3"

# Repo
ROOT_DIR="/home/jiaxuanluo/InfiniSST"

# Base sweep script (baseline, no RAG)
BASE_SCRIPT="${ROOT_DIR}/documents/code/simuleval/rank16/baseline/bypass_simuleval_rank32_iter_0000452_hf_baseline_no_rag_sweep.sh"

# Dataset
DATA_ROOT="/mnt/taurus/data/siqiouyang/datasets/acl6060"
LANG_CODE_DEFAULT="zh"
LANG_CODE_OVERRIDE="${LANG_CODE_OVERRIDE:-}"
LANG_CODE="${LANG_CODE_DEFAULT}"
TARGET_LANG_OVERRIDE="${TARGET_LANG_OVERRIDE:-}"

# Per-paper glossaries (already generated by extract_acl_terms_from_paper_v2.py)
EXTRACTED_GLOSSARIES_DIR="${ROOT_DIR}/documents/data/data_pre/extracted_glossaries_by_paper"
EXTRACTED_GLOSSARY_MANIFEST="${ROOT_DIR}/documents/data/data_pre/extracted_glossary_by_paper_manifest.json"

# Output base (keep everything colocated with results)
OUTPUT_BASE_DEFAULT="/mnt/gemini/data2/jiaxuanluo/infinisst_omni_vllm_rank16_baseline_no_rag"
OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE_OVERRIDE:-}"
OUTPUT_BASE="${OUTPUT_BASE_DEFAULT}"

# Where to put per-paper artifacts (subset lists + mapping json + combined lists)
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"

# Combined run settings
REQUIRED_PAPER_COUNT="5"
DEFAULT_PAPER_IDS="2022.acl-long.110 2022.acl-long.117 2022.acl-long.268 2022.acl-long.367 2022.acl-long.590"
PAPER_IDS_OVERRIDE="${PAPER_IDS_OVERRIDE:-}"
COMBINED_TAG_DEFAULT="combined_5papers_test"
COMBINED_TAG_OVERRIDE="${COMBINED_TAG_OVERRIDE:-}"
PYTHON_IO_ENCODING="utf-8"

# Pass-through overrides to base sweep script (optional)
LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE:-}"
RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE:-}"  # kept for output naming compatibility
MODEL_NAME_OVERRIDE="${MODEL_NAME_OVERRIDE:-}"
RESUME_MODE="${RESUME_MODE:-0}"
CLEAN_OUTPUT_DIR_OVERRIDE="${CLEAN_OUTPUT_DIR_OVERRIDE:-}"
BACKUP_PARTIAL_RUNS="${BACKUP_PARTIAL_RUNS:-}"

# GPU selection override for base script (physical ids, e.g. "2,3")
CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE="${CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE:-4,5}"
# ======Configuration=====

if [[ -n "${LANG_CODE_OVERRIDE}" ]]; then
  LANG_CODE="${LANG_CODE_OVERRIDE}"
fi

if [[ -n "${OUTPUT_BASE_OVERRIDE}" ]]; then
  OUTPUT_BASE="${OUTPUT_BASE_OVERRIDE}"
fi

COMBINED_TAG="${COMBINED_TAG_DEFAULT}"
if [[ -n "${COMBINED_TAG_OVERRIDE}" ]]; then
  COMBINED_TAG="${COMBINED_TAG_OVERRIDE}"
fi

# Keep derived paths consistent after overrides.
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"

if [[ ! -f "${BASE_SCRIPT}" ]]; then
  echo "[ERROR] Base script not found: ${BASE_SCRIPT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -d "${DATA_ROOT}" ]]; then
  echo "[ERROR] DATA_ROOT not found: ${DATA_ROOT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -d "${EXTRACTED_GLOSSARIES_DIR}" ]]; then
  echo "[ERROR] Extracted glossaries dir not found: ${EXTRACTED_GLOSSARIES_DIR}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${EXTRACTED_GLOSSARY_MANIFEST}" ]]; then
  echo "[ERROR] Manifest not found: ${EXTRACTED_GLOSSARY_MANIFEST}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

PREP_SCRIPT="${ROOT_DIR}/documents/code/simuleval/prepare_extracted_glossary_by_paper_inputs.py"
if [[ ! -f "${PREP_SCRIPT}" ]]; then
  echo "[ERROR] Prepare script not found: ${PREP_SCRIPT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi

mkdir -p "${PAPER_INPUTS_DIR}"

echo "[INFO] Preparing per-paper dev lists (using pre-generated glossaries)..."
python3 "${PREP_SCRIPT}" \
  --extracted-glossaries-dir "${EXTRACTED_GLOSSARIES_DIR}" \
  --extracted-glossary-manifest "${EXTRACTED_GLOSSARY_MANIFEST}" \
  --data-root "${DATA_ROOT}" \
  --lang-code "${LANG_CODE}" \
  --output-dir "${PAPER_INPUTS_DIR}"

MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"
if [[ ! -f "${MAP_JSON}" ]]; then
  echo "[ERROR] Mapping JSON not found: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

PAPERS="${DEFAULT_PAPER_IDS}"
if [[ -n "${PAPER_IDS_OVERRIDE}" ]]; then
  PAPERS="${PAPER_IDS_OVERRIDE}"
fi

# Count papers from the local bash variable (do not rely on env export).
PAPER_COUNT="0"
read -r -a PAPER_IDS_ARRAY <<<"${PAPERS}"
PAPER_COUNT="${#PAPER_IDS_ARRAY[@]}"
if [[ "${PAPER_COUNT}" != "${REQUIRED_PAPER_COUNT}" ]]; then
  echo "[ERROR] This script requires exactly ${REQUIRED_PAPER_COUNT} paper_ids, got ${PAPER_COUNT}: ${PAPERS}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi

COMBINED_SRC_LIST="${PAPER_INPUTS_DIR}/${COMBINED_TAG}.source"
COMBINED_TGT_LIST="${PAPER_INPUTS_DIR}/${COMBINED_TAG}.target.${LANG_CODE}"
COMBINED_GLOSSARY_PATH="${PAPER_INPUTS_DIR}/${COMBINED_TAG}.glossary.json"

echo "[INFO] OUTPUT_BASE=${OUTPUT_BASE}"
echo "[INFO] LANG_CODE=${LANG_CODE} TARGET_LANG_OVERRIDE='${TARGET_LANG_OVERRIDE:-<none>}'"
echo "[INFO] Baseline mode: RAG is disabled."
echo "[INFO] Papers to combine: ${PAPERS}"
echo "[INFO] Combined SRC_LIST=${COMBINED_SRC_LIST}"
echo "[INFO] Combined TGT_LIST=${COMBINED_TGT_LIST}"
echo "[INFO] Combined GLOSSARY_PATH(for naming)=${COMBINED_GLOSSARY_PATH}"
echo "[INFO] Overrides: lm='${LATENCY_MULTIPLIERS_OVERRIDE:-<none>}' k2='${RAG_K2_VALUES_OVERRIDE:-<none>}' resume='${RESUME_MODE}' model='${MODEL_NAME_OVERRIDE:-<default>}'"

export PAPERS
export MAP_JSON
export COMBINED_SRC_LIST
export COMBINED_TGT_LIST
export COMBINED_GLOSSARY_PATH
export COMBINED_TAG
export LANG_CODE
export PYTHON_IO_ENCODING

python3 - <<'PY'
import json
import os
from pathlib import Path

map_json=Path(os.environ["MAP_JSON"])
papers=os.environ["PAPERS"].split()
src_out=Path(os.environ["COMBINED_SRC_LIST"])
tgt_out=Path(os.environ["COMBINED_TGT_LIST"])
gloss_out=Path(os.environ["COMBINED_GLOSSARY_PATH"])
combined_tag=os.environ["COMBINED_TAG"]
lang_code=os.environ["LANG_CODE"]
encoding=os.environ.get("PYTHON_IO_ENCODING","utf-8")

obj=json.loads(map_json.read_text(encoding=encoding))
paper_map=obj.get("papers",{})

src_out.parent.mkdir(parents=True, exist_ok=True)
tgt_out.parent.mkdir(parents=True, exist_ok=True)

src_out.write_text("", encoding=encoding)
tgt_out.write_text("", encoding=encoding)

missing=[]
with src_out.open("a", encoding=encoding) as src_f, tgt_out.open("a", encoding=encoding) as tgt_f:
    for pid in papers:
        item=paper_map.get(pid,{})
        src=item.get("src_list","")
        tgt=item.get("tgt_list","")
        if not src or not Path(src).is_file():
            missing.append(f"{pid}:src_list:{src}")
            continue
        if not tgt or not Path(tgt).is_file():
            missing.append(f"{pid}:tgt_list:{tgt}")
            continue
        src_f.write(Path(src).read_text(encoding=encoding))
        tgt_f.write(Path(tgt).read_text(encoding=encoding))

if missing:
    raise SystemExit("[ERROR] Missing paper inputs: " + "; ".join(missing))

meta={
    "type": "combined_paper_test",
    "tag": combined_tag,
    "lang_code": lang_code,
    "paper_ids": papers,
}
gloss_out.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding=encoding)
PY

if [[ ! -s "${COMBINED_SRC_LIST}" ]] || [[ ! -s "${COMBINED_TGT_LIST}" ]]; then
  echo "[ERROR] Combined src/tgt list is empty: ${COMBINED_SRC_LIST} or ${COMBINED_TGT_LIST}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${COMBINED_GLOSSARY_PATH}" ]]; then
  echo "[ERROR] Combined glossary file not found: ${COMBINED_GLOSSARY_PATH}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

echo "[INFO] ============================================================"
echo "[INFO] Running combined test once: tag=${COMBINED_TAG}"

GLOSSARY_PATHS_OVERRIDE="${COMBINED_GLOSSARY_PATH}" \
SRC_LIST_OVERRIDE="${COMBINED_SRC_LIST}" \
TGT_LIST_OVERRIDE="${COMBINED_TGT_LIST}" \
OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE}" \
MODEL_NAME_OVERRIDE="${MODEL_NAME_OVERRIDE}" \
LANG_CODE_OVERRIDE="${LANG_CODE}" \
TARGET_LANG_OVERRIDE="${TARGET_LANG_OVERRIDE}" \
LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE}" \
RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE}" \
CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE="${CUDA_VISIBLE_DEVICES_PHYSICAL_OVERRIDE}" \
CLEAN_OUTPUT_DIR_OVERRIDE="${CLEAN_OUTPUT_DIR_OVERRIDE}" \
BACKUP_PARTIAL_RUNS="${BACKUP_PARTIAL_RUNS}" \
RESUME_MODE="${RESUME_MODE}" \
bash "${BASE_SCRIPT}"

echo "[INFO] Done."

