#!/usr/bin/env python3
"""Create Speech LLM SFT data with LLM-generated target-term variants.

V16 is a less artificial version of the V15 marker augmentation.  It keeps the
same atomic replacement rule:

* the GT term must appear in the current chunk term_map;
* the canonical target translation must occur exactly in assistant text from the
  current chunk onward;
* when selected, both the term_map value and the first future assistant exact
  occurrence are replaced.

The replacement is generated by an OpenAI chat model and cached by
``(source term, canonical translation)``.  The API key is read only from
``OPENAI_API_KEY`` and is never written to outputs.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import time
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple


def _iter_jsonl(path: Path) -> Iterable[Tuple[int, Dict[str, Any]]]:
    with path.open("r", encoding="utf-8", errors="replace") as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on {path}:{lineno}: {exc}") from exc
            if not isinstance(obj, dict):
                raise ValueError(f"Expected JSON object on {path}:{lineno}")
            yield lineno, obj


def _term_key(term: str) -> str:
    return " ".join(str(term or "").casefold().split())


def _variant_key(term: str, translation: str) -> str:
    return json.dumps({"term": term.strip(), "translation": translation.strip()}, ensure_ascii=False, sort_keys=True)


def _extract_translation(entry: Mapping[str, Any], lang_code: str) -> str:
    value = entry.get("translation") or entry.get("target_translation") or entry.get(lang_code)
    if value is None and isinstance(entry.get("target_translations"), Mapping):
        value = entry["target_translations"].get(lang_code)
    return str(value or "").strip()


def _set_translation(entry: MutableMapping[str, Any], lang_code: str, value: str) -> None:
    if lang_code in entry:
        entry[lang_code] = value
    elif "translation" in entry:
        entry["translation"] = value
    elif "target_translation" in entry:
        entry["target_translation"] = value
    else:
        entry[lang_code] = value
    target_translations = entry.get("target_translations")
    if isinstance(target_translations, MutableMapping):
        target_translations[lang_code] = value


def _audio_user_indices(messages: Sequence[Mapping[str, Any]]) -> List[int]:
    out = []
    for idx, msg in enumerate(messages):
        if msg.get("role") == "user" and "<audio>" in str(msg.get("content") or ""):
            out.append(idx)
    return out


def _parse_term_map(content: str) -> Dict[str, Tuple[int, str, str]]:
    out: Dict[str, Tuple[int, str, str]] = {}
    for idx, line in enumerate(str(content or "").splitlines()):
        if not line or line.strip() == "term_map:" or line.startswith("<audio>"):
            continue
        if "=" not in line:
            continue
        term, translation = line.split("=", 1)
        term = term.strip()
        translation = translation.strip()
        key = _term_key(term)
        if term and translation and key and key not in out:
            out[key] = (idx, term, translation)
    return out


def _replace_term_map_line(content: str, line_idx: int, term: str, new_translation: str) -> str:
    lines = str(content or "").splitlines()
    if line_idx < 0 or line_idx >= len(lines):
        raise ValueError(f"term_map line index out of range: {line_idx}")
    lines[line_idx] = f"{term}={new_translation}"
    return "\n".join(lines)


def _future_assistant_contains(messages: Sequence[Mapping[str, Any]], start_idx: int, text: str) -> bool:
    for msg_idx in range(start_idx, len(messages)):
        msg = messages[msg_idx]
        if msg.get("role") == "assistant" and text in str(msg.get("content") or ""):
            return True
    return False


def _find_and_replace_future_assistant(
    messages: Sequence[MutableMapping[str, Any]],
    start_idx: int,
    old: str,
    new: str,
) -> Optional[int]:
    for msg_idx in range(start_idx, len(messages)):
        msg = messages[msg_idx]
        if msg.get("role") != "assistant":
            continue
        content = str(msg.get("content") or "")
        if old not in content:
            continue
        msg["content"] = content.replace(old, new, 1)
        return msg_idx
    return None


def _selected_candidates(
    obj: Dict[str, Any],
    *,
    row_line: int,
    lang_code: str,
    augment_prob: float,
    rng: random.Random,
    max_augmented_terms_per_row: int,
    missing_gt_policy: str,
    stats: Counter,
) -> List[Dict[str, Any]]:
    messages = obj.get("messages")
    audios = obj.get("audios")
    gt_by_chunk = obj.get("gt_terms_by_chunk")
    if not isinstance(messages, list) or not isinstance(audios, list):
        raise ValueError("missing messages or audios")
    if not isinstance(gt_by_chunk, list):
        stats["rows_missing_gt_terms_by_chunk"] += 1
        stats["chunks_missing_gt_terms_by_chunk"] += len(audios) if isinstance(audios, list) else 0
        if missing_gt_policy == "keep_unchanged":
            stats["rows_seen"] += 1
            stats["chunks_total"] += len(audios) if isinstance(audios, list) else 0
            return []
        raise ValueError("missing gt_terms_by_chunk")
    audio_user_idxs = _audio_user_indices(messages)
    if len(audio_user_idxs) != len(audios):
        raise ValueError(f"audio user messages={len(audio_user_idxs)} audios={len(audios)}")
    if len(gt_by_chunk) != len(audios):
        raise ValueError(f"gt_terms_by_chunk={len(gt_by_chunk)} audios={len(audios)}")

    selected: List[Dict[str, Any]] = []
    row_selected = 0
    stats["rows_seen"] += 1
    stats["chunks_total"] += len(audios)
    for chunk_idx, msg_idx in enumerate(audio_user_idxs):
        raw_terms = gt_by_chunk[chunk_idx]
        if not isinstance(raw_terms, list):
            raise ValueError("gt_terms_by_chunk entry must be list")
        term_map = _parse_term_map(str(messages[msg_idx].get("content") or ""))
        if term_map:
            stats["chunks_with_nonempty_term_map"] += 1
        if raw_terms:
            stats["chunks_with_gt_terms"] += 1
        for term_pos, term_obj in enumerate(raw_terms):
            if not isinstance(term_obj, Mapping):
                raise ValueError("gt term entry must be object")
            term = str(term_obj.get("term") or term_obj.get("source") or "").strip()
            translation = _extract_translation(term_obj, lang_code)
            key = _term_key(term)
            if not term or not translation or not key:
                continue
            stats["candidate_gt_terms"] += 1
            if key not in term_map:
                stats["skipped_gt_not_in_current_term_map"] += 1
                continue
            stats["candidate_gt_terms_in_current_term_map"] += 1
            if not _future_assistant_contains(messages, msg_idx + 1, translation):
                stats["skipped_missing_future_reference_exact"] += 1
                continue
            stats["candidate_gt_terms_with_future_reference_exact"] += 1
            if max_augmented_terms_per_row > 0 and row_selected >= max_augmented_terms_per_row:
                stats["skipped_row_cap"] += 1
                continue
            if rng.random() >= augment_prob:
                stats["skipped_by_probability"] += 1
                continue
            line_idx, map_term, map_translation = term_map[key]
            selected.append({
                "row_line": row_line,
                "chunk_idx": chunk_idx,
                "term_pos": term_pos,
                "msg_idx": msg_idx,
                "term": term,
                "term_key": key,
                "translation": translation,
                "term_map_line_idx": line_idx,
                "term_map_surface": map_term,
                "term_map_translation": map_translation,
            })
            row_selected += 1
            stats["selected_terms"] += 1
    if row_selected:
        stats["rows_with_selected_terms"] += 1
    return selected


def _load_cache(path: Path) -> Dict[str, Dict[str, Any]]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        obj = json.load(f)
    if not isinstance(obj, dict):
        raise ValueError(f"Variant cache must be a JSON object: {path}")
    out: Dict[str, Dict[str, Any]] = {}
    for key, value in obj.items():
        if isinstance(value, Mapping):
            out[str(key)] = dict(value)
    return out


def _write_json_atomic(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    tmp.write_text(json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def _clean_variant(text: str) -> str:
    text = str(text or "").strip()
    text = re.sub(r"^[\"'“”‘’`]+|[\"'“”‘’`]+$", "", text).strip()
    text = re.sub(r"\s+", " ", text)
    return text


def _validate_variant(translation: str, variant: str) -> Tuple[bool, str]:
    variant = _clean_variant(variant)
    if not variant:
        return False, "empty"
    if variant == translation:
        return False, "identity"
    if "__tm" in variant or "<term" in variant or "</term>" in variant:
        return False, "marker_like"
    if "\n" in variant or "=" in variant:
        return False, "bad_delimiter"
    if len(variant) > max(18, len(translation) * 4 + 8):
        return False, "too_long"
    if len(variant) < 1:
        return False, "too_short"
    return True, ""


def _openai_chat_json(
    *,
    api_key: str,
    model: str,
    lang_code: str,
    batch: List[Dict[str, str]],
    timeout: int,
    max_retries: int,
) -> List[Dict[str, str]]:
    lang_name = {"zh": "Chinese", "de": "German", "ja": "Japanese"}.get(lang_code, lang_code)
    system = (
        f"You create {lang_name} terminology variants for a speech translation SFT dataset. "
        f"For each English source term and canonical {lang_name} translation, return a natural, "
        f"fluent {lang_name} alternative that is less common than the canonical form but still "
        "semantically correct in a translated sentence. Do not add explanations, IDs outside "
        "the requested schema, quotes, XML, suffix markers, romanization, or English unless the "
        "canonical translation itself contains English or units. Keep variants short."
    )
    user = {
        "task": f"Generate one {lang_name} target variant for each item.",
        "constraints": [
            "variant must be different from canonical_translation",
            f"variant must be a natural {lang_name} phrase, not a random marker",
            "variant must preserve the meaning of source_term in context-free terminology translation",
            "variant should be uncommon enough that copying from term_map is useful",
            "return strict JSON only: {\"items\":[{\"id\":...,\"variant\":...}]}",
        ],
        "items": batch,
    }
    payload = {
        "model": model,
        "temperature": 0.7,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": json.dumps(user, ensure_ascii=False)},
        ],
    }
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    last_error: Optional[BaseException] = None
    for attempt in range(max_retries + 1):
        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            data=data,
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                raw = resp.read().decode("utf-8")
            obj = json.loads(raw)
            content = obj["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            items = parsed.get("items")
            if not isinstance(items, list):
                raise ValueError("OpenAI response JSON missing items list")
            return [dict(x) for x in items if isinstance(x, Mapping)]
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, KeyError, json.JSONDecodeError, ValueError) as exc:
            last_error = exc
            sleep_s = min(60.0, 2.0 * (2 ** attempt))
            if attempt < max_retries:
                time.sleep(sleep_s)
    raise RuntimeError(f"OpenAI batch failed after retries: {last_error}") from last_error


def generate_variant_cache(
    *,
    selected_terms: List[Dict[str, Any]],
    cache_path: Path,
    lang_code: str,
    model: str,
    batch_size: int,
    timeout: int,
    max_retries: int,
    max_api_items: int,
    dry_run: bool,
    cache_only: bool,
) -> Dict[str, Dict[str, Any]]:
    cache = _load_cache(cache_path)
    unique: Dict[str, Dict[str, str]] = {}
    for item in selected_terms:
        term = str(item["term"]).strip()
        translation = str(item["translation"]).strip()
        key = _variant_key(term, translation)
        if key in cache and cache[key].get("status") == "ok":
            continue
        unique.setdefault(key, {"term": term, "translation": translation})

    pending = list(unique.items())
    if max_api_items > 0:
        pending = pending[:max_api_items]
    if not pending:
        return cache
    if cache_only:
        print(json.dumps({
            "cache_path": str(cache_path),
            "cache_only": True,
            "pending_missing_from_cache": len(pending),
            "cache_total": len(cache),
        }, ensure_ascii=False), flush=True)
        return cache
    if dry_run:
        for key, item in pending:
            cache[key] = {
                "status": "ok",
                "source_term": item["term"],
                "canonical_translation": item["translation"],
                "variant": f"{item['translation']}异译",
                "model": "dry_run",
            }
        _write_json_atomic(cache_path, cache)
        return cache

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is required for V16 variant generation")

    for start in range(0, len(pending), batch_size):
        chunk = pending[start:start + batch_size]
        batch = [
            {
                "id": str(i),
                "source_term": item["term"],
                "canonical_translation": item["translation"],
            }
            for i, (_, item) in enumerate(chunk)
        ]
        results = _openai_chat_json(
            api_key=api_key,
            model=model,
            lang_code=lang_code,
            batch=batch,
            timeout=timeout,
            max_retries=max_retries,
        )
        by_id = {str(x.get("id")): x for x in results}
        for i, (key, item) in enumerate(chunk):
            raw_variant = str(by_id.get(str(i), {}).get("variant") or "")
            variant = _clean_variant(raw_variant)
            ok, reason = _validate_variant(item["translation"], variant)
            if ok:
                cache[key] = {
                    "status": "ok",
                    "source_term": item["term"],
                    "canonical_translation": item["translation"],
                    "variant": variant,
                    "model": model,
                }
            else:
                cache[key] = {
                    "status": "invalid",
                    "source_term": item["term"],
                    "canonical_translation": item["translation"],
                    "raw_variant": raw_variant,
                    "reason": reason,
                    "model": model,
                }
        _write_json_atomic(cache_path, cache)
        print(json.dumps({
            "cache_path": str(cache_path),
            "generated": min(start + len(chunk), len(pending)),
            "pending_total": len(pending),
            "cache_total": len(cache),
        }, ensure_ascii=False), flush=True)
        time.sleep(0.2)
    return cache


def collect_selected_terms(args: argparse.Namespace) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    stats: Counter = Counter()
    rng = random.Random(args.seed)
    selected: List[Dict[str, Any]] = []
    for row_line, obj in _iter_jsonl(args.input_jsonl):
        if args.max_rows > 0 and stats["rows_seen"] >= args.max_rows:
            break
        selected.extend(_selected_candidates(
            obj,
            row_line=row_line,
            lang_code=args.lang_code,
            augment_prob=args.augment_prob,
            rng=rng,
            max_augmented_terms_per_row=args.max_augmented_terms_per_row,
            missing_gt_policy=args.missing_gt_policy,
            stats=stats,
        ))
    total = stats["candidate_gt_terms"]
    in_map = stats["candidate_gt_terms_in_current_term_map"]
    future = stats["candidate_gt_terms_with_future_reference_exact"]
    selected_n = stats["selected_terms"]
    stats_dict: Dict[str, Any] = dict(stats)
    stats_dict.update({
        "input_jsonl": str(args.input_jsonl),
        "lang_code": args.lang_code,
        "augment_prob": args.augment_prob,
        "seed": args.seed,
        "max_augmented_terms_per_row": args.max_augmented_terms_per_row,
        "gt_term_in_current_term_map_rate": in_map / total if total else 0.0,
        "future_reference_exact_rate_over_gt_terms": future / total if total else 0.0,
        "selected_over_gt_terms_rate": selected_n / total if total else 0.0,
        "selected_over_gt_in_map_rate": selected_n / in_map if in_map else 0.0,
    })
    return selected, stats_dict


def apply_variants(
    args: argparse.Namespace,
    *,
    cache: Mapping[str, Mapping[str, Any]],
    sample_count: int,
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    stats: Counter = Counter()
    samples: List[Dict[str, Any]] = []
    rng = random.Random(args.seed)
    args.output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    with args.output_jsonl.open("w", encoding="utf-8") as fout:
        for row_line, obj in _iter_jsonl(args.input_jsonl):
            if args.max_rows > 0 and stats["rows_written"] >= args.max_rows:
                break
            selected = _selected_candidates(
                obj,
                row_line=row_line,
                lang_code=args.lang_code,
                augment_prob=args.augment_prob,
                rng=rng,
                max_augmented_terms_per_row=args.max_augmented_terms_per_row,
                missing_gt_policy=args.missing_gt_policy,
                stats=stats,
            )
            messages = obj["messages"]
            gt_by_chunk = obj.get("gt_terms_by_chunk") or []
            row_events: List[Dict[str, Any]] = []
            for item in selected:
                cache_key = _variant_key(str(item["term"]), str(item["translation"]))
                cached = cache.get(cache_key)
                if not cached or cached.get("status") != "ok":
                    stats["skipped_missing_or_invalid_variant"] += 1
                    continue
                variant = _clean_variant(str(cached.get("variant") or ""))
                ok, reason = _validate_variant(str(item["translation"]), variant)
                if not ok:
                    stats[f"skipped_invalid_variant_{reason}"] += 1
                    continue
                chunk_idx = int(item["chunk_idx"])
                msg_idx = int(item["msg_idx"])
                term_pos = int(item["term_pos"])
                term_map_surface = str(item["term_map_surface"])
                line_idx = int(item["term_map_line_idx"])
                translation = str(item["translation"])
                replaced_msg_idx = _find_and_replace_future_assistant(
                    messages,
                    start_idx=msg_idx + 1,
                    old=translation,
                    new=variant,
                )
                if replaced_msg_idx is None:
                    stats["skipped_missing_future_reference_exact_apply"] += 1
                    continue
                messages[msg_idx]["content"] = _replace_term_map_line(
                    str(messages[msg_idx].get("content") or ""),
                    line_idx=line_idx,
                    term=term_map_surface,
                    new_translation=variant,
                )
                _set_translation(gt_by_chunk[chunk_idx][term_pos], args.lang_code, variant)
                stats["augmented_terms"] += 1
                stats["assistant_replacements"] += 1
                stats["term_map_replacements"] += 1
                event = {
                    "chunk_idx": chunk_idx,
                    "term": str(item["term"]),
                    "old_translation": translation,
                    "new_translation": variant,
                    "assistant_msg_idx": replaced_msg_idx,
                }
                row_events.append(event)
                if len(samples) < sample_count:
                    samples.append({"row_line": row_line, "utter_id": obj.get("utter_id"), **event})
            if row_events:
                stats["rows_with_augmentation"] += 1
            obj["term_translation_llm_variant_augmentation"] = {
                "version": "v16_openai_v1",
                "lang_code": args.lang_code,
                "augment_prob": args.augment_prob,
                "model": args.openai_model,
                "max_augmented_terms_per_row": args.max_augmented_terms_per_row,
                "missing_gt_policy": args.missing_gt_policy,
                "cache_only": args.cache_only,
                "augmented_terms_in_row": len(row_events),
                "events": row_events[:50],
            }
            fout.write(json.dumps(obj, ensure_ascii=False) + "\n")
            stats["rows_written"] += 1

    total = stats["candidate_gt_terms"]
    in_map = stats["candidate_gt_terms_in_current_term_map"]
    selected_n = stats["selected_terms"]
    augmented = stats["augmented_terms"]
    stats_dict: Dict[str, Any] = dict(stats)
    stats_dict.update({
        "input_jsonl": str(args.input_jsonl),
        "output_jsonl": str(args.output_jsonl),
        "variant_cache_json": str(args.variant_cache_json),
        "lang_code": args.lang_code,
        "augment_prob": args.augment_prob,
        "seed": args.seed,
        "openai_model": args.openai_model,
        "max_augmented_terms_per_row": args.max_augmented_terms_per_row,
        "gt_term_in_current_term_map_rate": in_map / total if total else 0.0,
        "selected_over_gt_terms_rate": selected_n / total if total else 0.0,
        "augmented_over_gt_terms_rate": augmented / total if total else 0.0,
        "augmented_over_selected_rate": augmented / selected_n if selected_n else 0.0,
        "augmented_over_gt_in_map_rate": augmented / in_map if in_map else 0.0,
    })
    return stats_dict, samples


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-jsonl", type=Path, required=True)
    parser.add_argument("--output-jsonl", type=Path, required=True)
    parser.add_argument("--stats-json", type=Path, required=True)
    parser.add_argument("--variant-cache-json", type=Path, required=True)
    parser.add_argument("--sample-json", type=Path, default=None)
    parser.add_argument("--lang-code", default="zh")
    parser.add_argument("--augment-prob", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=1606)
    parser.add_argument("--max-augmented-terms-per-row", type=int, default=8)
    parser.add_argument("--sample-count", type=int, default=80)
    parser.add_argument("--openai-model", default=os.environ.get("OPENAI_MODEL", "gpt-4.1-mini"))
    parser.add_argument("--openai-batch-size", type=int, default=40)
    parser.add_argument("--openai-timeout", type=int, default=90)
    parser.add_argument("--openai-max-retries", type=int, default=4)
    parser.add_argument("--max-api-items", type=int, default=0)
    parser.add_argument("--max-rows", type=int, default=0)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--cache-only",
        action="store_true",
        help=(
            "Do not call OpenAI for missing variants.  Existing ok cache entries "
            "are applied and uncached selected terms are reported/skipped."
        ),
    )
    parser.add_argument(
        "--missing-gt-policy",
        choices=["error", "keep_unchanged"],
        default="error",
        help=(
            "Policy for legacy rows without gt_terms_by_chunk.  The default is "
            "fail-fast; keep_unchanged writes those rows unchanged and reports "
            "counters."
        ),
    )
    args = parser.parse_args()

    if not args.input_jsonl.is_file():
        raise FileNotFoundError(args.input_jsonl)
    if not (0.0 <= args.augment_prob <= 1.0):
        raise ValueError("--augment-prob must be in [0, 1]")
    if args.openai_batch_size <= 0:
        raise ValueError("--openai-batch-size must be positive")

    args.output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    args.stats_json.parent.mkdir(parents=True, exist_ok=True)
    args.variant_cache_json.parent.mkdir(parents=True, exist_ok=True)
    if args.sample_json:
        args.sample_json.parent.mkdir(parents=True, exist_ok=True)

    selected, selection_stats = collect_selected_terms(args)
    cache = generate_variant_cache(
        selected_terms=selected,
        cache_path=args.variant_cache_json,
        lang_code=args.lang_code,
        model=args.openai_model,
        batch_size=args.openai_batch_size,
        timeout=args.openai_timeout,
        max_retries=args.openai_max_retries,
        max_api_items=args.max_api_items,
        dry_run=args.dry_run,
        cache_only=args.cache_only,
    )
    stats_dict, samples = apply_variants(args, cache=cache, sample_count=args.sample_count)
    stats_dict["selection_pass"] = selection_stats
    args.stats_json.write_text(
        json.dumps(stats_dict, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    if args.sample_json:
        args.sample_json.write_text(
            json.dumps(samples, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    print(json.dumps(stats_dict, ensure_ascii=False, indent=2, sort_keys=True), flush=True)


if __name__ == "__main__":
    main()
