#!/usr/bin/env bash
set -euo pipefail

# Aggregate StreamLAAL TERM_ACC across per-paper runs and compute overall term accuracy.
#
# Overall term accuracy definition in this script:
#   sum(correct_terms_per_talk) / sum(total_terms_per_paper)
#
# All user-facing strings are in English.

# ======Configuration=====
# Exit codes
EXIT_CONFIG_ERROR="2"
EXIT_DATA_ERROR="3"

# Repo
ROOT_DIR="/home/jiaxuanluo/InfiniSST"

# SimulEval outputs
OUTPUT_BASE="/mnt/gemini/data2/jiaxuanluo/infinisst_omni_vllm_rag_rank32_iter_0000452_hf_zh_k1_10_k2_sweep_glossary2"
LANG_CODE="zh"
OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE_OVERRIDE:-}"
LANG_CODE_OVERRIDE="${LANG_CODE_OVERRIDE:-}"

# Optional: restrict papers (space-separated paper_ids). Empty means all papers in mapping.
PAPER_IDS_OVERRIDE="${PAPER_IDS_OVERRIDE:-}"

# Per-paper inputs map (generated by prepare_extracted_glossary_by_paper_inputs.py)
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"
MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"

# Fixed settings (must match your SimulEval run)
LATENCY_MULTIPLIERS=("1" "2" "3" "4")
RAG_K2_VALUES=("5" "10" "15" "20")
RAG_K1_FIXED="10"
RAG_HOP_SIZE="0.48"
RAG_CONFIDENCE_THRESHOLD="0.0"
RAG_CONFIDENCE_THRESHOLD_OVERRIDE="${RAG_CONFIDENCE_THRESHOLD_OVERRIDE:-}"
LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE:-}"
RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE:-}"

# Reference and audio
REF_FULL="/mnt/taurus/data/siqiouyang/datasets/acl6060/dev/text/txt/ACL.6060.dev.en-xx.zh.txt"
SOURCE_FULL="/mnt/taurus/data/siqiouyang/datasets/acl6060/dev/text/txt/ACL.6060.dev.en-xx.en.txt"
AUDIO_YAML_FULL="/mnt/taurus/data/siqiouyang/datasets/acl6060/dev.yaml"

# StreamLAAL tool
FBK_FAIRSEQ_ROOT="/mnt/taurus/home/jiaxuanluo/FBK-fairseq"
STREAM_LAAL_TOOL_REL="examples/speech_to_text/simultaneous_translation/scripts/stream_laal_term.py"
SACREBLEU_TOKENIZER="zh"
LATENCY_UNIT="char"
TERM_LANG="zh"
TERM_MISMATCH_EXAMPLES="0"

# MWER segmenter
MWERSEGMENTER_ROOT="/mnt/taurus/home/jiaxuanluo/mwerSegmenter"

# Conda env
CONDA_BASE="/mnt/taurus/home/jiaxuanluo/miniconda3"
CONDA_ENV_NAME="spaCyEnv"
# ======Configuration=====

if [[ -n "${OUTPUT_BASE_OVERRIDE}" ]]; then
  OUTPUT_BASE="${OUTPUT_BASE_OVERRIDE}"
fi
if [[ -n "${LANG_CODE_OVERRIDE}" ]]; then
  LANG_CODE="${LANG_CODE_OVERRIDE}"
fi

# Keep derived paths consistent after overrides.
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"
MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"

if [[ ! -f "${MAP_JSON}" ]]; then
  echo "[ERROR] Mapping JSON not found: ${MAP_JSON}" >&2
  echo "[ERROR] Run prepare_extracted_glossary_by_paper_inputs.py first." >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${REF_FULL}" ]]; then
  echo "[ERROR] REF_FULL not found: ${REF_FULL}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${SOURCE_FULL}" ]]; then
  echo "[ERROR] SOURCE_FULL not found: ${SOURCE_FULL}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${AUDIO_YAML_FULL}" ]]; then
  echo "[ERROR] AUDIO_YAML_FULL not found: ${AUDIO_YAML_FULL}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

STREAM_LAAL_TOOL="${FBK_FAIRSEQ_ROOT}/${STREAM_LAAL_TOOL_REL}"
if [[ ! -f "${STREAM_LAAL_TOOL}" ]]; then
  echo "[ERROR] stream_laal_term.py not found: ${STREAM_LAAL_TOOL}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi

# shellcheck disable=SC1090
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV_NAME}"

export MWERSEGMENTER_ROOT
export PATH="${MWERSEGMENTER_ROOT}:${PATH}"

# Apply overrides
if [[ -n "${RAG_CONFIDENCE_THRESHOLD_OVERRIDE}" ]]; then
  RAG_CONFIDENCE_THRESHOLD="${RAG_CONFIDENCE_THRESHOLD_OVERRIDE}"
fi
if [[ -n "${LATENCY_MULTIPLIERS_OVERRIDE}" ]]; then
  # shellcheck disable=SC2206
  LATENCY_MULTIPLIERS=(${LATENCY_MULTIPLIERS_OVERRIDE})
fi
if [[ -n "${RAG_K2_VALUES_OVERRIDE}" ]]; then
  # shellcheck disable=SC2206
  RAG_K2_VALUES=(${RAG_K2_VALUES_OVERRIDE})
fi

# Output dir tag for threshold (match the run script)
THRESHOLD_TAG="${RAG_CONFIDENCE_THRESHOLD//./p}"

# We will compute total terms from stream_laal_term.py outputs:
# sum(total_terms_per_paper)

echo "[INFO] Scanning papers from mapping..."
PAPERS="$(
python3 - <<PY
import json
mp = "${MAP_JSON}"
with open(mp, "r", encoding="utf-8") as f:
    obj = json.load(f)
print(" ".join(sorted(obj.get("papers", {}).keys())))
PY
)"

if [[ -z "${PAPERS}" ]]; then
  echo "[ERROR] No papers found in mapping: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

if [[ -n "${PAPER_IDS_OVERRIDE}" ]]; then
  PAPERS="${PAPER_IDS_OVERRIDE}"
fi

for LATENCY_MULTIPLIER in "${LATENCY_MULTIPLIERS[@]}"; do
  for RAG_K2 in "${RAG_K2_VALUES[@]}"; do
    echo "[INFO] ============================================================"
    echo "[INFO] Aggregating: lm=${LATENCY_MULTIPLIER} k2=${RAG_K2} th=${RAG_CONFIDENCE_THRESHOLD}"

    total_correct="0"
    total_terms="0"
    adoption_adopted="0"
    adoption_total="0"
    adoption_sentences="0"
    adoption_weighted_sum="0.0"

    for PAPER_ID in ${PAPERS}; do
      echo "[INFO] ------------------------------------------------------------"
      echo "[INFO] Paper: ${PAPER_ID}"

      GLOSSARY_PATH="$(
      python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp, "r", encoding="utf-8") as f:
    obj=json.load(f)
item=obj.get("papers", {}).get(pid, {})
print(item.get("glossary_path", ""))
PY
      )"

      if [[ -z "${GLOSSARY_PATH}" ]] || [[ ! -f "${GLOSSARY_PATH}" ]]; then
        echo "[WARN] Skip paper_id=${PAPER_ID}: glossary_path missing: ${GLOSSARY_PATH}" >&2
        continue
      fi

      GLOSSARY_TAG="$(basename "${GLOSSARY_PATH}" .json)"

      # Find the newest matching output dir (ignore partial backups via mtime ordering).
      # Use nullglob to avoid literal '*' when no matches.
      shopt -s nullglob
      MATCHES=(
        "${OUTPUT_BASE}/${LANG_CODE}"/*_g${GLOSSARY_TAG}_cs*_hs${RAG_HOP_SIZE}_lm${LATENCY_MULTIPLIER}_k2${RAG_K2}_k1${RAG_K1_FIXED}_th${THRESHOLD_TAG}
      )
      shopt -u nullglob

      OUTPUT_DIR=""
      if [[ "${#MATCHES[@]}" -gt 0 ]]; then
        OUTPUT_DIR="$(ls -dt "${MATCHES[@]}" 2>/dev/null | head -n 1 || true)"
      fi

      if [[ -z "${OUTPUT_DIR}" ]]; then
        echo "[WARN] Output dir not found for paper_id=${PAPER_ID} (lm=${LATENCY_MULTIPLIER} k2=${RAG_K2} th=${RAG_CONFIDENCE_THRESHOLD})" >&2
        continue
      fi

      INSTANCES_PATH="${OUTPUT_DIR}/instances.log"
      if [[ ! -f "${INSTANCES_PATH}" ]] || [[ ! -s "${INSTANCES_PATH}" ]]; then
        echo "[WARN] Missing/empty instances.log: ${INSTANCES_PATH}" >&2
        continue
      fi

      # Build per-paper audio/ref files aligned with dev.yaml and full reference
      python3 - <<PY
from pathlib import Path
import yaml

out_dir = Path("${OUTPUT_DIR}")
audio_yaml = Path("${AUDIO_YAML_FULL}")
ref_full = Path("${REF_FULL}")
source_full = Path("${SOURCE_FULL}")

paper_wav = "${PAPER_ID}.wav"

with audio_yaml.open("r", encoding="utf-8") as f:
    data = yaml.safe_load(f)
with ref_full.open("r", encoding="utf-8") as f:
    refs = [line.rstrip("\n") for line in f]
with source_full.open("r", encoding="utf-8") as f:
    sources = [line.rstrip("\n") for line in f]

if len(data) != len(refs):
    raise RuntimeError(f"dev.yaml entries {len(data)} != reference lines {len(refs)}")
if len(data) != len(sources):
    raise RuntimeError(f"dev.yaml entries {len(data)} != source lines {len(sources)}")

indices = [i for i, x in enumerate(data) if isinstance(x, dict) and x.get("wav") == paper_wav]
subset_audio = [data[i] for i in indices]
subset_refs = [refs[i] for i in indices]
subset_sources = [sources[i] for i in indices]

out_audio = out_dir / f"audio_{paper_wav.replace('.wav','')}.yaml"
out_ref = out_dir / f"ref_{paper_wav.replace('.wav','')}.txt"
out_source = out_dir / f"source_{paper_wav.replace('.wav','')}.txt"

out_audio.write_text(yaml.safe_dump(subset_audio, allow_unicode=True), encoding="utf-8")
out_ref.write_text("\n".join(subset_refs) + "\n", encoding="utf-8")
out_source.write_text("\n".join(subset_sources) + "\n", encoding="utf-8")

print(str(out_audio))
print(str(out_ref))
print(str(out_source))
PY

      AUDIO_SUB="${OUTPUT_DIR}/audio_${PAPER_ID}.yaml"
      REF_SUB="${OUTPUT_DIR}/ref_${PAPER_ID}.txt"
      SOURCE_SUB="${OUTPUT_DIR}/source_${PAPER_ID}.txt"

      if [[ ! -f "${AUDIO_SUB}" ]] || [[ ! -f "${REF_SUB}" ]] || [[ ! -f "${SOURCE_SUB}" ]]; then
        echo "[WARN] Missing per-paper audio/ref/source files in ${OUTPUT_DIR}" >&2
        continue
      fi

      set +e
      EVAL_OUT="$(${CONDA_BASE}/envs/${CONDA_ENV_NAME}/bin/python "${STREAM_LAAL_TOOL}" \
        --simuleval-instances "${INSTANCES_PATH}" \
        --reference "${REF_SUB}" \
        --audio-yaml "${AUDIO_SUB}" \
        --sacrebleu-tokenizer "${SACREBLEU_TOKENIZER}" \
        --latency-unit "${LATENCY_UNIT}" \
        --glossary "${GLOSSARY_PATH}" \
        --term-lang "${TERM_LANG}" \
        --term-mismatch-examples "${TERM_MISMATCH_EXAMPLES}" 2>&1)"
      EVAL_RC="$?"
      set -e

      if [[ "${EVAL_RC}" != "0" ]]; then
        echo "[WARN] stream_laal_term.py failed for ${PAPER_ID} (rc=${EVAL_RC})" >&2
        echo "${EVAL_OUT}" >&2
        continue
      fi

      TERM_LINE="$(echo "${EVAL_OUT}" | awk '/^TERM_ACC[[:space:]]/{print; exit}')"
      TERM_CORRECT="$(echo "${TERM_LINE}" | awk '{print $4}')"
      TERM_TOTAL="$(echo "${TERM_LINE}" | awk '{print $6}')"

      if [[ -z "${TERM_CORRECT}" ]] || [[ -z "${TERM_TOTAL}" ]]; then
        echo "[WARN] TERM_CORRECT or TERM_TOTAL not found for ${PAPER_ID}" >&2
        continue
      fi

      ADOPTION_OUT="$(${CONDA_BASE}/envs/${CONDA_ENV_NAME}/bin/python "/mnt/taurus/home/jiaxuanluo/InfiniSST/documents/code/offline_sst_eval/compute_sentence_term_adoption.py" \
        --instances-log "${INSTANCES_PATH}" \
        --source-file "${SOURCE_SUB}" \
        --reference-file "${REF_SUB}" \
        --glossary-path "${GLOSSARY_PATH}" \
        --target-lang "${TERM_LANG}" \
        --output-json "${OUTPUT_DIR}/term_adoption.json" 2>&1 || true)"
      echo "${ADOPTION_OUT}" > "${OUTPUT_DIR}/term_adoption.log"

      ADOPTION_LINE="$(echo "${ADOPTION_OUT}" | awk '/^TERM_ADOPTION[[:space:]]/{print; exit}')"
      ADOPTED_COUNT="$(echo "${ADOPTION_LINE}" | awk '{print $4}')"
      ADOPTION_TERM_TOTAL="$(echo "${ADOPTION_LINE}" | awk '{print $6}')"
      ADOPTION_SENT_COUNT="$(echo "${ADOPTION_LINE}" | awk '{print $8}')"
      ADOPTION_MACRO="$(echo "${ADOPTION_LINE}" | awk '{print $2}')"

      if [[ -z "${ADOPTED_COUNT}" ]] || [[ -z "${ADOPTION_TERM_TOTAL}" ]] || [[ -z "${ADOPTION_SENT_COUNT}" ]] || [[ -z "${ADOPTION_MACRO}" ]]; then
        ADOPTED_COUNT="0"
        ADOPTION_TERM_TOTAL="0"
        ADOPTION_SENT_COUNT="0"
        ADOPTION_MACRO="0.0"
      fi

      total_correct="$((total_correct + TERM_CORRECT))"
      total_terms="$((total_terms + TERM_TOTAL))"
      adoption_adopted="$((adoption_adopted + ADOPTED_COUNT))"
      adoption_total="$((adoption_total + ADOPTION_TERM_TOTAL))"
      adoption_sentences="$((adoption_sentences + ADOPTION_SENT_COUNT))"
      adoption_weighted_sum="$(python3 - <<PYINNER
old = float("${adoption_weighted_sum}")
macro = float("${ADOPTION_MACRO}")
sent = int("${ADOPTION_SENT_COUNT}")
print(f"{old + macro * sent:.12f}")
PYINNER
)"

      echo "${EVAL_OUT}" > "${OUTPUT_DIR}/post_eval_streamlaal_term.log"
      echo "[INFO] ${PAPER_ID} TERM_CORRECT=${TERM_CORRECT} TERM_TOTAL=${TERM_TOTAL} TERM_ADOPTION=${ADOPTION_MACRO} ADOPTED=${ADOPTED_COUNT}/${ADOPTION_TERM_TOTAL} SENTENCES=${ADOPTION_SENT_COUNT}"
    done

    if [[ "${total_terms}" -le 0 ]]; then
      echo "[ERROR] Invalid total term count: ${total_terms}" >&2
      continue
    fi

    python3 - <<PY
correct = ${total_correct}
total = ${total_terms}
adopted = ${adoption_adopted}
adoption_total = ${adoption_total}
sentences = ${adoption_sentences}
weighted = float("${adoption_weighted_sum}")
acc = correct / total if total > 0 else 0.0
adoption_macro = weighted / sentences if sentences > 0 else 0.0
adoption_micro = adopted / adoption_total if adoption_total > 0 else 0.0
print(f"[INFO] Overall TERM_ACC = {acc:.6f} (sum_correct={correct}, total_terms={total})")
print(f"[INFO] Overall TERM_ADOPTION = {adoption_macro:.6f} (adopted={adopted}, total_terms={adoption_total}, sentences={sentences}, micro={adoption_micro:.6f})")
PY
  done
done
