#!/usr/bin/env bash
set -euo pipefail

# Run SimulEval for the "paper extracted glossary" but *per talk/paper*:
# - Split extracted glossary into per-paper sub-glossaries using `source_paper`
# - Split dev.source/dev.target into per-paper subsets using wav id
# - For each paper_id, run the existing sweep script by overriding:
#   - GLOSSARY_PATHS_OVERRIDE
#   - SRC_LIST_OVERRIDE / TGT_LIST_OVERRIDE
#
# All user-facing strings are in English.

# ======Configuration=====
# Exit codes
EXIT_CONFIG_ERROR="2"
EXIT_DATA_ERROR="3"

# Repo
ROOT_DIR="/home/jiaxuanluo/InfiniSST"
BASE_SCRIPT="${ROOT_DIR}/documents/code/simuleval/bypass_simuleval_rank32_iter_0000452_hf_zh_k1_10_k2_sweep_glossary2.sh"

# Dataset
DATA_ROOT="/mnt/taurus/data/siqiouyang/datasets/acl6060"
LANG_CODE="zh"

# Per-paper glossaries (already generated by extract_acl_terms_from_paper_v2.py)
EXTRACTED_GLOSSARIES_DIR="/home/jiaxuanluo/InfiniSST/documents/data/data_pre/extracted_glossaries_by_paper"
EXTRACTED_GLOSSARY_MANIFEST="/home/jiaxuanluo/InfiniSST/documents/data/data_pre/extracted_glossary_by_paper_manifest.json"

# Where to put per-paper artifacts (subset lists + mapping json)
# Default is under OUTPUT_BASE/zh to keep everything colocated with results.
OUTPUT_BASE="/mnt/gemini/data2/jiaxuanluo/infinisst_omni_vllm_rag_rank32_iter_0000452_hf_zh_k1_10_k2_sweep_glossary2"
OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE_OVERRIDE:-}"
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"

# Optional: restrict papers (space-separated paper_ids). Empty means all papers in dev.source.
PAPER_IDS_OVERRIDE="${PAPER_IDS_OVERRIDE:-}"

# Pass-through overrides to base sweep script (optional)
LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE:-}"
RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE:-}"
RAG_CONFIDENCE_THRESHOLD_OVERRIDE="${RAG_CONFIDENCE_THRESHOLD_OVERRIDE:-}"
RAG_CONFIDENCE_THRESHOLD_MODE_OVERRIDE="${RAG_CONFIDENCE_THRESHOLD_MODE_OVERRIDE:-}"
RESUME_MODE="${RESUME_MODE:-0}"
CLEAN_OUTPUT_DIR_OVERRIDE="${CLEAN_OUTPUT_DIR_OVERRIDE:-}"
BACKUP_PARTIAL_RUNS="${BACKUP_PARTIAL_RUNS:-}"
# ======Configuration=====

if [[ -n "${OUTPUT_BASE_OVERRIDE}" ]]; then
  OUTPUT_BASE="${OUTPUT_BASE_OVERRIDE}"
  PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"
fi

if [[ ! -f "${BASE_SCRIPT}" ]]; then
  echo "[ERROR] Base script not found: ${BASE_SCRIPT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -d "${DATA_ROOT}" ]]; then
  echo "[ERROR] DATA_ROOT not found: ${DATA_ROOT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -d "${EXTRACTED_GLOSSARIES_DIR}" ]]; then
  echo "[ERROR] Extracted glossaries dir not found: ${EXTRACTED_GLOSSARIES_DIR}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${EXTRACTED_GLOSSARY_MANIFEST}" ]]; then
  echo "[WARN] Manifest not found: ${EXTRACTED_GLOSSARY_MANIFEST} (will scan dir)" >&2
fi

PREP_SCRIPT="${ROOT_DIR}/documents/code/simuleval/prepare_extracted_glossary_by_paper_inputs.py"
if [[ ! -f "${PREP_SCRIPT}" ]]; then
  echo "[ERROR] Prepare script not found: ${PREP_SCRIPT}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi

mkdir -p "${PAPER_INPUTS_DIR}"

echo "[INFO] Preparing per-paper dev lists (using pre-generated glossaries)..."
python3 "${PREP_SCRIPT}" \
  --extracted-glossaries-dir "${EXTRACTED_GLOSSARIES_DIR}" \
  --extracted-glossary-manifest "${EXTRACTED_GLOSSARY_MANIFEST}" \
  --data-root "${DATA_ROOT}" \
  --lang-code "${LANG_CODE}" \
  --output-dir "${PAPER_INPUTS_DIR}"

MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"
if [[ ! -f "${MAP_JSON}" ]]; then
  echo "[ERROR] Mapping JSON not found: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

PAPERS="$(
python3 - <<PY
import json
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
papers=obj.get('papers',{})
print(" ".join(sorted(papers.keys())))
PY
)"

if [[ -z "${PAPERS}" ]]; then
  echo "[ERROR] No papers prepared from mapping: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

if [[ -n "${PAPER_IDS_OVERRIDE}" ]]; then
  PAPERS="${PAPER_IDS_OVERRIDE}"
fi

echo "[INFO] Papers to run: ${PAPERS}"

for PAPER_ID in ${PAPERS}; do
  GLOSSARY_PATH="$(
  python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
papers=obj.get('papers',{})
item=papers.get(pid,{})
print(item.get('glossary_path',''))
PY
  )"
  SRC_LIST_OVERRIDE_LOCAL="$(
  python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
papers=obj.get('papers',{})
item=papers.get(pid,{})
print(item.get('src_list',''))
PY
  )"
  TGT_LIST_OVERRIDE_LOCAL="$(
  python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp,'r',encoding='utf-8') as f:
    obj=json.load(f)
papers=obj.get('papers',{})
item=papers.get(pid,{})
print(item.get('tgt_list',''))
PY
  )"

  if [[ -z "${GLOSSARY_PATH}" ]] || [[ ! -f "${GLOSSARY_PATH}" ]]; then
    echo "[WARN] Skip paper_id=${PAPER_ID}: glossary_path missing: ${GLOSSARY_PATH}" >&2
    continue
  fi
  if [[ -z "${SRC_LIST_OVERRIDE_LOCAL}" ]] || [[ ! -f "${SRC_LIST_OVERRIDE_LOCAL}" ]]; then
    echo "[WARN] Skip paper_id=${PAPER_ID}: src_list missing: ${SRC_LIST_OVERRIDE_LOCAL}" >&2
    continue
  fi
  if [[ -z "${TGT_LIST_OVERRIDE_LOCAL}" ]] || [[ ! -f "${TGT_LIST_OVERRIDE_LOCAL}" ]]; then
    echo "[WARN] Skip paper_id=${PAPER_ID}: tgt_list missing: ${TGT_LIST_OVERRIDE_LOCAL}" >&2
    continue
  fi

  echo "[INFO] ============================================================"
  echo "[INFO] Running paper_id=${PAPER_ID}"
  echo "[INFO] GLOSSARY_PATH=${GLOSSARY_PATH}"
  echo "[INFO] SRC_LIST_OVERRIDE=${SRC_LIST_OVERRIDE_LOCAL}"
  echo "[INFO] TGT_LIST_OVERRIDE=${TGT_LIST_OVERRIDE_LOCAL}"

  echo "[INFO] Overrides: latency=${LATENCY_MULTIPLIERS_OVERRIDE:-<none>} k2=${RAG_K2_VALUES_OVERRIDE:-<none>} threshold=${RAG_CONFIDENCE_THRESHOLD_OVERRIDE:-<none>} threshold_mode=${RAG_CONFIDENCE_THRESHOLD_MODE_OVERRIDE:-<none>} resume=${RESUME_MODE}"

  GLOSSARY_PATHS_OVERRIDE="${GLOSSARY_PATH}" \
  SRC_LIST_OVERRIDE="${SRC_LIST_OVERRIDE_LOCAL}" \
  TGT_LIST_OVERRIDE="${TGT_LIST_OVERRIDE_LOCAL}" \
  OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE_OVERRIDE}" \
  LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE}" \
  RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE}" \
  RAG_CONFIDENCE_THRESHOLD_OVERRIDE="${RAG_CONFIDENCE_THRESHOLD_OVERRIDE}" \
  RAG_CONFIDENCE_THRESHOLD_MODE_OVERRIDE="${RAG_CONFIDENCE_THRESHOLD_MODE_OVERRIDE}" \
  CLEAN_OUTPUT_DIR_OVERRIDE="${CLEAN_OUTPUT_DIR_OVERRIDE}" \
  BACKUP_PARTIAL_RUNS="${BACKUP_PARTIAL_RUNS}" \
  RESUME_MODE="${RESUME_MODE}" \
  bash "${BASE_SCRIPT}"
done

echo "[INFO] Done."


