#!/usr/bin/env bash
set -euo pipefail

# Aggregate StreamLAAL TERM_ACC across per-paper runs (rank16 output directory naming) and compute overall term accuracy.
#
# Overall term accuracy definition in this script:
#   sum(correct_terms_per_talk) / sum(total_terms_per_talk)
#
# All user-facing strings are in English.

# ======Configuration=====
# Exit codes
EXIT_CONFIG_ERROR="2"
EXIT_DATA_ERROR="3"

# Repo
ROOT_DIR="/home/jiaxuanluo/InfiniSST"

# SimulEval outputs
OUTPUT_BASE="/mnt/gemini/data2/jiaxuanluo/infinisst_omni_vllm_rag_rank16_v3-20260121-021342-hf_zh_k1_10_k2_sweep_glossary2"
LANG_CODE="zh"
OUTPUT_BASE_OVERRIDE="${OUTPUT_BASE_OVERRIDE:-}"
LANG_CODE_OVERRIDE="${LANG_CODE_OVERRIDE:-}"

# Optional: restrict output directory matching to a specific model.
# If provided, we will only match output dirs whose prefix equals basename(MODEL_NAME_OVERRIDE).
MODEL_NAME_OVERRIDE="${MODEL_NAME_OVERRIDE:-}"

# Optional: restrict papers (space-separated paper_ids). Empty means all papers in mapping.
PAPER_IDS_OVERRIDE="${PAPER_IDS_OVERRIDE:-}"

# Per-paper inputs map (generated by prepare_extracted_glossary_by_paper_inputs.py)
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"
MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"

# Fixed settings (must match your SimulEval run)
LATENCY_MULTIPLIERS=("1" "2" "3" "4")
RAG_K2_VALUES=("5" "10" "15" "20")
RAG_K1_FIXED="${RAG_K1_FIXED:-10}"
RAG_HOP_SIZE="0.48"
RAG_CONFIDENCE_THRESHOLD="0.0"
RAG_CONFIDENCE_THRESHOLD_OVERRIDE="${RAG_CONFIDENCE_THRESHOLD_OVERRIDE:-}"
LATENCY_MULTIPLIERS_OVERRIDE="${LATENCY_MULTIPLIERS_OVERRIDE:-}"
RAG_K2_VALUES_OVERRIDE="${RAG_K2_VALUES_OVERRIDE:-}"
GLOSSARY_SIZE_OVERRIDE="${GLOSSARY_SIZE_OVERRIDE:-0}"
EXPANDED_GLOSSARIES_DIR="${EXPANDED_GLOSSARIES_DIR:-/home/jiaxuanluo/InfiniSST/documents/data/data_pre/expanded_glossaries_by_paper}"

# RAG eval mode / intersection strategy used during inference (for logging only).
RAG_EVAL_MODE="intersection"
RAG_EVAL_MODE_OVERRIDE="${RAG_EVAL_MODE_OVERRIDE:-}"
RAG_INTERSECTION_STRATEGY="pool_then_intersect"
RAG_INTERSECTION_STRATEGY_OVERRIDE="${RAG_INTERSECTION_STRATEGY_OVERRIDE:-}"

# Reference and audio
DATA_ROOT="/mnt/taurus/data/siqiouyang/datasets/acl6060"
REF_FULL="${DATA_ROOT}/dev/text/txt/ACL.6060.dev.en-xx.${LANG_CODE}.txt"
AUDIO_YAML_FULL="${DATA_ROOT}/dev.yaml"

# StreamLAAL tool
FBK_FAIRSEQ_ROOT="/mnt/taurus/home/jiaxuanluo/FBK-fairseq"
STREAM_LAAL_TOOL_REL="examples/speech_to_text/simultaneous_translation/scripts/stream_laal_term.py"
TERM_MISMATCH_EXAMPLES="0"
SIGNIFICANT_DIGITS="4"
GLOSSARY_FOR_FULL_METRICS="${GLOSSARY_FOR_FULL_METRICS:-/mnt/taurus/home/jiaxuanluo/InfiniSST/retriever/gigaspeech/data_pre/glossary_acl6060.json}"

# MWER segmenter
MWERSEGMENTER_ROOT="/mnt/taurus/home/jiaxuanluo/mwerSegmenter"

# Conda env (must have simuleval + dependencies)
CONDA_BASE="/home/jiaxuanluo/miniconda3"
CONDA_ENV_NAME="infinisst"
# ======Configuration=====

if [[ -n "${OUTPUT_BASE_OVERRIDE}" ]]; then
  OUTPUT_BASE="${OUTPUT_BASE_OVERRIDE}"
fi
if [[ -n "${LANG_CODE_OVERRIDE}" ]]; then
  LANG_CODE="${LANG_CODE_OVERRIDE}"
fi

# Tokenizer/latency unit by language (baseline-aligned)
SACREBLEU_TOKENIZER=""
LATENCY_UNIT=""
TERM_LANG="${LANG_CODE}"
if [[ "${LANG_CODE}" == "zh" ]]; then
  SACREBLEU_TOKENIZER="zh"
  LATENCY_UNIT="char"
elif [[ "${LANG_CODE}" == "ja" ]]; then
  SACREBLEU_TOKENIZER="ja-mecab"
  LATENCY_UNIT="char"
elif [[ "${LANG_CODE}" == "de" ]]; then
  SACREBLEU_TOKENIZER="13a"
  LATENCY_UNIT="word"
else
  echo "[ERROR] Unsupported LANG_CODE: ${LANG_CODE}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi

# If MODEL_NAME_OVERRIDE is set, constrain output dir search to this model.
MODEL_SHORT_GLOB="*"
if [[ -n "${MODEL_NAME_OVERRIDE}" ]]; then
  MODEL_SHORT_GLOB="$(basename "${MODEL_NAME_OVERRIDE}")"
fi

# Keep derived paths consistent after overrides.
PAPER_INPUTS_DIR="${OUTPUT_BASE}/${LANG_CODE}/__paper_inputs__"
MAP_JSON="${PAPER_INPUTS_DIR}/paper_inputs_map.json"
REF_FULL="${DATA_ROOT}/dev/text/txt/ACL.6060.dev.en-xx.${LANG_CODE}.txt"

if [[ ! -f "${MAP_JSON}" ]]; then
  echo "[ERROR] Mapping JSON not found: ${MAP_JSON}" >&2
  echo "[ERROR] Run prepare_extracted_glossary_by_paper_inputs.py first." >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${REF_FULL}" ]]; then
  echo "[ERROR] REF_FULL not found: ${REF_FULL}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ ! -f "${AUDIO_YAML_FULL}" ]]; then
  echo "[ERROR] AUDIO_YAML_FULL not found: ${AUDIO_YAML_FULL}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

STREAM_LAAL_TOOL="${FBK_FAIRSEQ_ROOT}/${STREAM_LAAL_TOOL_REL}"
if [[ ! -f "${STREAM_LAAL_TOOL}" ]]; then
  echo "[ERROR] stream_laal_term.py not found: ${STREAM_LAAL_TOOL}" >&2
  exit "${EXIT_CONFIG_ERROR}"
fi
if [[ ! -f "${GLOSSARY_FOR_FULL_METRICS}" ]]; then
  echo "[ERROR] GLOSSARY_FOR_FULL_METRICS not found: ${GLOSSARY_FOR_FULL_METRICS}" >&2
  exit "${EXIT_DATA_ERROR}"
fi

# shellcheck disable=SC1090
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV_NAME}"
echo "[INFO] Activated conda env: ${CONDA_ENV_NAME}"

export MWERSEGMENTER_ROOT
export PATH="${MWERSEGMENTER_ROOT}:${PATH}"

# Apply overrides
if [[ -n "${RAG_CONFIDENCE_THRESHOLD_OVERRIDE}" ]]; then
  RAG_CONFIDENCE_THRESHOLD="${RAG_CONFIDENCE_THRESHOLD_OVERRIDE}"
fi
if [[ -n "${LATENCY_MULTIPLIERS_OVERRIDE}" ]]; then
  # shellcheck disable=SC2206
  LATENCY_MULTIPLIERS=(${LATENCY_MULTIPLIERS_OVERRIDE})
fi
if [[ -n "${RAG_K2_VALUES_OVERRIDE}" ]]; then
  # shellcheck disable=SC2206
  RAG_K2_VALUES=(${RAG_K2_VALUES_OVERRIDE})
fi
if [[ -n "${RAG_EVAL_MODE_OVERRIDE}" ]]; then
  RAG_EVAL_MODE="${RAG_EVAL_MODE_OVERRIDE}"
fi
#intersect_then_pool
if [[ -n "${RAG_INTERSECTION_STRATEGY_OVERRIDE}" ]]; then
  RAG_INTERSECTION_STRATEGY="${RAG_INTERSECTION_STRATEGY_OVERRIDE}"
fi

# Output dir tag for threshold (match the run script)
THRESHOLD_TAG="${RAG_CONFIDENCE_THRESHOLD//./p}"

echo "[INFO] Scanning papers from mapping..."
PAPERS="$(
python3 - <<PY
import json
mp = "${MAP_JSON}"
with open(mp, "r", encoding="utf-8") as f:
    obj = json.load(f)
print(" ".join(sorted(obj.get("papers", {}).keys())))
PY
)"

if [[ -z "${PAPERS}" ]]; then
  echo "[ERROR] No papers found in mapping: ${MAP_JSON}" >&2
  exit "${EXIT_DATA_ERROR}"
fi
if [[ -n "${PAPER_IDS_OVERRIDE}" ]]; then
  PAPERS="${PAPER_IDS_OVERRIDE}"
fi

echo "[INFO] OUTPUT_BASE=${OUTPUT_BASE}"
echo "[INFO] LANG_CODE=${LANG_CODE} TOKENIZER=${SACREBLEU_TOKENIZER} LATENCY_UNIT=${LATENCY_UNIT}"
echo "[INFO] RAG_EVAL_MODE=${RAG_EVAL_MODE} INTERSECTION_STRATEGY=${RAG_INTERSECTION_STRATEGY}"
echo "[INFO] MODEL_SHORT_GLOB=${MODEL_SHORT_GLOB} (from MODEL_NAME_OVERRIDE='${MODEL_NAME_OVERRIDE:-<none>}')"
echo "[INFO] Papers: ${PAPERS}"

for LATENCY_MULTIPLIER in "${LATENCY_MULTIPLIERS[@]}"; do
  for RAG_K2 in "${RAG_K2_VALUES[@]}"; do
    echo "[INFO] ============================================================"
    echo "[INFO] Aggregating: lm=${LATENCY_MULTIPLIER} k2=${RAG_K2} th=${RAG_CONFIDENCE_THRESHOLD}"

    total_correct="0"
    total_terms="0"
    bleu_sum="0"
    bleu_count="0"
    combined_instances="$(mktemp -t combined_instances_lm${LATENCY_MULTIPLIER}_k2${RAG_K2}_XXXXXX.log)"
    combined_wav_count="0"

    for PAPER_ID in ${PAPERS}; do
      GLOSSARY_PATH="$(
      python3 - <<PY
import json
pid="${PAPER_ID}"
mp="${MAP_JSON}"
with open(mp, "r", encoding="utf-8") as f:
    obj=json.load(f)
item=obj.get("papers", {}).get(pid, {})
print(item.get("glossary_path", ""))
PY
      )"

      if [[ -z "${GLOSSARY_PATH}" ]] || [[ ! -f "${GLOSSARY_PATH}" ]]; then
        echo "[WARN] Skip paper_id=${PAPER_ID}: glossary_path missing: ${GLOSSARY_PATH}" >&2
        continue
      fi

      if [[ "${GLOSSARY_SIZE_OVERRIDE}" -gt 0 ]]; then
        GLOSSARY_TAG="expanded_glossary__${PAPER_ID}_gs${GLOSSARY_SIZE_OVERRIDE}"
      else
        GLOSSARY_TAG="$(basename "${GLOSSARY_PATH}" .json)"
      fi

      # Rank16 output naming does not include iter_ prefix; match by suffix fields + glossary tag.
      # MODEL_SHORT_GLOB may contain '*'; must be unquoted for glob expansion.
      SEARCH_GLOB="${OUTPUT_BASE}/${LANG_CODE}/${MODEL_SHORT_GLOB}_g${GLOSSARY_TAG}_cs*_hs${RAG_HOP_SIZE}_lm${LATENCY_MULTIPLIER}_k2${RAG_K2}_k1${RAG_K1_FIXED}_th${THRESHOLD_TAG}"
      set +e
      # shellcheck disable=SC2086
      OUTPUT_DIR="$(ls -dt ${SEARCH_GLOB} 2>/dev/null | head -n 1)"
      LS_RC="$?"
      set -e

      if [[ "${LS_RC}" != "0" ]] || [[ -z "${OUTPUT_DIR}" ]]; then
        echo "[ERROR] Output dir not found for paper_id=${PAPER_ID} (lm=${LATENCY_MULTIPLIER} k2=${RAG_K2} th=${RAG_CONFIDENCE_THRESHOLD})" >&2
        echo "[ERROR] Expected pattern: ${OUTPUT_BASE}/${LANG_CODE}/${MODEL_SHORT_GLOB}_g${GLOSSARY_TAG}_cs*_hs${RAG_HOP_SIZE}_lm${LATENCY_MULTIPLIER}_k2${RAG_K2}_k1${RAG_K1_FIXED}_th${THRESHOLD_TAG}" >&2
        exit "${EXIT_DATA_ERROR}"
      fi

      INSTANCES_PATH="${OUTPUT_DIR}/instances.log"
      if [[ ! -f "${INSTANCES_PATH}" ]] || [[ ! -s "${INSTANCES_PATH}" ]]; then
        echo "[WARN] Missing/empty instances.log: ${INSTANCES_PATH}" >&2
        continue
      fi

      # Build per-paper audio/ref files aligned with dev.yaml and full reference
      python3 - <<PY
from pathlib import Path
import yaml

out_dir = Path("${OUTPUT_DIR}")
audio_yaml = Path("${AUDIO_YAML_FULL}")
ref_full = Path("${REF_FULL}")

paper_wav = "${PAPER_ID}.wav"

data = yaml.safe_load(audio_yaml.read_text(encoding="utf-8", errors="replace"))
refs = ref_full.read_text(encoding="utf-8", errors="replace").splitlines()

if len(data) != len(refs):
    raise RuntimeError(f"dev.yaml entries {len(data)} != reference lines {len(refs)}")

indices = [i for i, x in enumerate(data) if isinstance(x, dict) and x.get("wav") == paper_wav]
subset_audio = [data[i] for i in indices]
subset_refs = [refs[i] for i in indices]

out_audio = out_dir / f"audio_{paper_wav.replace('.wav','')}.yaml"
out_ref = out_dir / f"ref_{paper_wav.replace('.wav','')}.txt"

out_audio.write_text(yaml.safe_dump(subset_audio, allow_unicode=True), encoding="utf-8")
out_ref.write_text("\\n".join(subset_refs) + "\\n", encoding="utf-8")
PY

      AUDIO_SUB="${OUTPUT_DIR}/audio_${PAPER_ID}.yaml"
      REF_SUB="${OUTPUT_DIR}/ref_${PAPER_ID}.txt"

      if [[ ! -f "${AUDIO_SUB}" ]] || [[ ! -f "${REF_SUB}" ]]; then
        echo "[WARN] Missing per-paper audio/ref files in ${OUTPUT_DIR}" >&2
        continue
      fi

      set +e
      EVAL_OUT="$(${CONDA_BASE}/envs/${CONDA_ENV_NAME}/bin/python "${STREAM_LAAL_TOOL}" \
        --simuleval-instances "${INSTANCES_PATH}" \
        --reference "${REF_SUB}" \
        --audio-yaml "${AUDIO_SUB}" \
        --sacrebleu-tokenizer "${SACREBLEU_TOKENIZER}" \
        --latency-unit "${LATENCY_UNIT}" \
        --glossary "${GLOSSARY_PATH}" \
        --term-lang "${TERM_LANG}" \
        --term-mismatch-examples "${TERM_MISMATCH_EXAMPLES}" 2>&1)"
      EVAL_RC="$?"
      set -e

      if [[ "${EVAL_RC}" != "0" ]]; then
        echo "[WARN] stream_laal_term.py failed for ${PAPER_ID} (rc=${EVAL_RC})" >&2
        echo "${EVAL_OUT}" >&2
        continue
      fi

      TERM_LINE="$(echo "${EVAL_OUT}" | awk '/^TERM_ACC[[:space:]]/{print; exit}')"
      TERM_CORRECT="$(echo "${TERM_LINE}" | awk '{print $4}')"
      TERM_TOTAL="$(echo "${TERM_LINE}" | awk '{print $6}')"
      BLEU_VALUES_LINE="$(echo "${EVAL_OUT}" | awk 'BEGIN{found=0} /^BLEU[[:space:]]/{found=1; next} found {print; exit}')"
      BLEU_SCORE="$(echo "${BLEU_VALUES_LINE}" | awk '{print $1}')"

      if [[ -z "${TERM_CORRECT}" ]] || [[ -z "${TERM_TOTAL}" ]]; then
        echo "[WARN] TERM_CORRECT or TERM_TOTAL not found for ${PAPER_ID}" >&2
        continue
      fi

      total_correct="$((total_correct + TERM_CORRECT))"
      total_terms="$((total_terms + TERM_TOTAL))"

      # Append this paper's instance line into a combined instances.log for computing overall BLEU/StreamLAAL metrics.
      python3 - <<PY
from pathlib import Path
src = Path("${INSTANCES_PATH}")
dst = Path("${combined_instances}")
text = src.read_text(encoding="utf-8", errors="replace")
if not text.endswith("\\n"):
    text += "\\n"
dst.write_text(dst.read_text(encoding="utf-8", errors="replace") + text if dst.exists() else text, encoding="utf-8")
PY
      combined_wav_count="$((combined_wav_count + 1))"

      echo "${EVAL_OUT}" > "${OUTPUT_DIR}/post_eval_streamlaal_term.log"
      echo "[INFO] ${PAPER_ID} TERM_CORRECT=${TERM_CORRECT} TERM_TOTAL=${TERM_TOTAL}"
      if [[ -z "${BLEU_SCORE}" ]]; then
        echo "[WARN] BLEU score not found for ${PAPER_ID}" >&2
      else
        bleu_sum="$(
        python3 - <<PY
prev = float("${bleu_sum}")
val = float("${BLEU_SCORE}")
print(prev + val)
PY
        )"
        bleu_count="$((bleu_count + 1))"
        echo "[INFO] ${PAPER_ID} BLEU=${BLEU_SCORE}"
      fi
    done

    if [[ "${total_terms}" -le 0 ]]; then
      echo "[ERROR] Invalid total term count: ${total_terms}" >&2
      rm -f "${combined_instances}"
      continue
    fi

    python3 - <<PY
correct = ${total_correct}
total = ${total_terms}
acc = correct / total if total > 0 else 0.0
digits = int("${SIGNIFICANT_DIGITS}")
print(f"[INFO] Overall TERM_ACC = {acc:.{digits}g} (sum_correct={correct}, total_terms={total})")
PY

    if [[ "${combined_wav_count}" -le 0 ]]; then
      echo "[WARN] Overall BLEU/StreamLAAL skipped: combined_wav_count=${combined_wav_count}" >&2
      rm -f "${combined_instances}"
      continue
    fi

    set +e
    FULL_OUT="$(${CONDA_BASE}/envs/${CONDA_ENV_NAME}/bin/python "${STREAM_LAAL_TOOL}" \
      --simuleval-instances "${combined_instances}" \
      --reference "${REF_FULL}" \
      --audio-yaml "${AUDIO_YAML_FULL}" \
      --sacrebleu-tokenizer "${SACREBLEU_TOKENIZER}" \
      --latency-unit "${LATENCY_UNIT}" \
      --glossary "${GLOSSARY_FOR_FULL_METRICS}" \
      --term-lang "${TERM_LANG}" \
      --term-mismatch-examples "${TERM_MISMATCH_EXAMPLES}" 2>&1)"
    FULL_RC="$?"
    set -e
    if [[ "${FULL_RC}" != "0" ]]; then
      echo "[WARN] Overall stream_laal_term.py failed (rc=${FULL_RC})" >&2
      echo "${FULL_OUT}" >&2
      rm -f "${combined_instances}"
      continue
    fi

    FULL_VALUES_LINE="$(echo "${FULL_OUT}" | awk 'BEGIN{found=0} /^BLEU[[:space:]]/{found=1; next} found {print; exit}')"
    FULL_BLEU="$(echo "${FULL_VALUES_LINE}" | awk '{print $1}')"
    FULL_STREAM_LAAL="$(echo "${FULL_VALUES_LINE}" | awk '{print $2}')"
    FULL_STREAM_LAAL_CA="$(echo "${FULL_VALUES_LINE}" | awk '{print $3}')"

    python3 - <<PY
bleu = float("${FULL_BLEU}")
laal = float("${FULL_STREAM_LAAL}")
laal_ca = float("${FULL_STREAM_LAAL_CA}")
digits = int("${SIGNIFICANT_DIGITS}")
wavs = int("${combined_wav_count}")
print(f"[INFO] Overall BLEU/StreamLAAL/StreamLAAL_CA = {bleu:.{digits}g}\t{laal:.{digits}g}\t{laal_ca:.{digits}g} (wavs={wavs})")
PY
    rm -f "${combined_instances}"

    if [[ "${bleu_count}" -le 0 ]]; then
      echo "[WARN] BLEU average skipped: bleu_count=${bleu_count}" >&2
      continue
    fi
    python3 - <<PY
bleu_sum = float("${bleu_sum}")
bleu_count = int("${bleu_count}")
avg = bleu_sum / bleu_count if bleu_count > 0 else 0.0
digits = int("${SIGNIFICANT_DIGITS}")
print(f"[INFO] Average BLEU = {avg:.{digits}g} (sum_bleu={bleu_sum}, count={bleu_count})")
PY
  done
done


